### ISSUE TITLE
More recommended Apps

### ISSUE THREAD

**Issue by fossdd** [Divested-Mobile/FOSS_Apps_List#1]
I've tested on my phone a lot of apps that are, of course, fully open-source and installed over the official F-Droid repository.

- [**openWorkout**](https://f-droid.org/en/packages/com.health.openworkout/)
- [**QKSMS**](https://f-droid.org/en/packages/com.moez.QKSMS/)
- [**Tasks.org**](https://f-droid.org/en/packages/org.tasks/)
- [**FreeOTP+**](https://f-droid.org/en/packages/org.liberty.android.freeotpplus/)
- [**Metro**](https://f-droid.org/en/packages/io.github.muntashirakon.Music/)
- [**GitNex**](https://f-droid.org/en/packages/org.mian.gitnex/)
- [**TubeLab**](https://f-droid.org/en/packages/app.fedilab.tubelab/)
- [**Husky**](https://f-droid.org/en/packages/su.xash.husky/)
- [**Clock+**](https://f-droid.org/packages/com.philliphsu.clock2/)
- [**Calculator++**](https://f-droid.org/en/packages/org.solovyev.android.calculator/)
- [**Just Player**](https://f-droid.org/en/packages/com.brouken.player/)
- [**Librera PRO**](https://f-droid.org/en/packages/com.foobnix.pro.pdf.reader/)
- [**Ning**](https://f-droid.org/en/packages/de.csicar.ning/)
- [**Twire**](https://f-droid.org/en/packages/com.perflyst.twire/)
- [**Material Files**](https://f-droid.org/en/packages/me.zhanghai.android.files/)
- [**Camera Roll**](https://f-droid.org/en/packages/us.koller.cameraroll/)

**Comment by SkewedZeppelin** [comment]
Thanks for the list.

- openWorkout has network access and seems to cover the same content as Sieben.
- QKSMS, I might consider adding it.
- Tasks.org used to be listed, but was removed in favor of openTasks. It seems
to have gotten a big overhaul, so I'll add it back.
- FreeOTP+ isn't needed when there is andOTP. andOTP notably uses the Android
Keystore for storage.
- Metro, a local music player doesn't need network access. Vanilla works just
fine.
- GitNex, I'll add it.
- TubeLab, I'll add it.
- Husky, there are a lot of Mastodon apps, and I don't have time to compare them
all. I'll leave this out for now.
- Clock+, hasn't been updated since 2017. Likely missing attributes to allow
alarms on encrypted devices.
- Calculator++, I'll have to look at this one more.
- Just (Video) Player, we already have VLC.
- Librera PRO, this was missing updates for a long while IIRC, seems it has been
resurrected. I'll give it a test and maybe add it.
- Ning, we already have Port Authority.
- Twire, I'll add it.
- Material Files, has network access.
- Camera Roll, this used to be bundled with DivestOS, it hasn't been updated in
a long while. And SimpleMobileTools Gallery is excellent.

For future, this list is actually stored here
https://github.com/Divested-Mobile/foss_apps_list
then I use `pandoc` to convert it to HTML and import it into this repo.

**Comment by fossdd** [comment]
Okay.

3 Jan 2021, 19:30 by notifications@github.com:

**Comment by Universalizer** [comment]
Hello, Dev,
I follow your official website time to time,

Please overview another repo here ; https://github.com/Psyhackological/AAA,

If possible, for your own review here, because personally, i want second opinion from expert or master in tech like you, more the opinion, more focusing,

👍Gratitude.
